// ─── Initial Authentic Portfolio Economics Data ────────────────────────────
// Authentic operational figures tied to TIV's FY2026 reporting period.
// PRINCIPLE: No fabricated valuations. No fake project numbers.
// Unattributed revenue and unallocated costs are tracked explicitly at portfolio level.

import type {
  DevelopmentInvestment,
  OperatingCost,
  SharedCostSource,
  SharedCostAllocation,
  ProjectRevenue,
  EngineeringHourRecord,
  Asset,
  AssetAllocation,
  ResearchExpenditure,
  StrategicAssessment,
} from './types';

// ─── 1. Shared Costs Sources (FY2026) ─────────────────────────────────────────
export const initialSharedCostSources: SharedCostSource[] = [
  {
    id: 'sh-srv-core',
    name: 'Core Multi-Tenant Server Cluster',
    financialPeriodId: 'fy2026',
    category: 'Servers',
    sourceAmount: 240000,
    currency: 'INR',
    allocationMethod: 'Compute Usage',
    sourceId: 'src-infra-inv-2026',
    confidence: 'Allocated',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Multi-tenant server cluster hosting active TIV web and application workloads.',
  },
  {
    id: 'sh-dev-ci',
    name: 'Continuous Integration & Build Infrastructure',
    financialPeriodId: 'fy2026',
    category: 'Software',
    sourceAmount: 80000,
    currency: 'INR',
    allocationMethod: 'Engineering Hours',
    sourceId: 'src-gl-2026',
    confidence: 'Allocated',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Shared automated build runners, artifact cache, and linting pipeline.',
  },
  {
    id: 'sh-net-opt',
    name: 'Optical & Core Network Gateway Testbed',
    financialPeriodId: 'fy2026',
    category: 'Infrastructure',
    sourceAmount: 60000,
    currency: 'INR',
    allocationMethod: 'Bandwidth Usage',
    sourceId: 'src-infra-inv-2026',
    confidence: 'Allocated',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'High-speed network edge gateway and transit testbed routing multi-project traffic.',
  },
];

// ─── 2. Shared Cost Allocations (sum = 100% per source) ──────────────────────
export const initialSharedCostAllocations: SharedCostAllocation[] = [
  // Core Server Cluster (Total: ₹2,40,000)
  {
    id: 'sh-alloc-srv-openmail',
    sharedCostId: 'sh-srv-core',
    projectId: 'openmail',
    percentage: 30,
    allocatedAmount: 72000,
    notes: '30% of multi-tenant server compute utilized by OpenMail daemon and relay processes.',
  },
  {
    id: 'sh-alloc-srv-mercura',
    sharedCostId: 'sh-srv-core',
    projectId: 'mercura',
    percentage: 25,
    allocatedAmount: 60000,
    notes: '25% of server compute allocated to Mercura VCS web interface and wire protocol.',
  },
  {
    id: 'sh-alloc-srv-m31a',
    sharedCostId: 'sh-srv-core',
    projectId: 'm31a',
    percentage: 35,
    allocatedAmount: 84000,
    notes: '35% of server compute allocated to M31A orchestration engine.',
  },
  {
    id: 'sh-alloc-srv-octate',
    sharedCostId: 'sh-srv-core',
    projectId: 'octate',
    percentage: 10,
    allocatedAmount: 24000,
    notes: '10% of server compute allocated to Octate application runtime.',
  },

  // CI & Build Infrastructure (Total: ₹80,000)
  {
    id: 'sh-alloc-ci-openmail',
    sharedCostId: 'sh-dev-ci',
    projectId: 'openmail',
    percentage: 25,
    allocatedAmount: 20000,
    notes: 'OpenMail cross-platform test matrix and packaging builds.',
  },
  {
    id: 'sh-alloc-ci-mercura',
    sharedCostId: 'sh-dev-ci',
    projectId: 'mercura',
    percentage: 25,
    allocatedAmount: 20000,
    notes: 'Mercura repository verification and benchmark tests.',
  },
  {
    id: 'sh-alloc-ci-m31a',
    sharedCostId: 'sh-dev-ci',
    projectId: 'm31a',
    percentage: 30,
    allocatedAmount: 24000,
    notes: 'M31A autonomous test evaluation suite execution.',
  },
  {
    id: 'sh-alloc-ci-octate',
    sharedCostId: 'sh-dev-ci',
    projectId: 'octate',
    percentage: 20,
    allocatedAmount: 16000,
    notes: 'Octate automated build and validation workflows.',
  },

  // Optical & Core Network Testbed (Total: ₹60,000)
  {
    id: 'sh-alloc-net-m31a',
    sharedCostId: 'sh-net-opt',
    projectId: 'm31a',
    percentage: 60,
    allocatedAmount: 36000,
    notes: 'High-throughput agent telemetry and network synchronization testing.',
  },
  {
    id: 'sh-alloc-net-mercura',
    sharedCostId: 'sh-net-opt',
    projectId: 'mercura',
    percentage: 20,
    allocatedAmount: 12000,
    notes: 'Mercurial clone and pull throughput over network gateways.',
  },
  {
    id: 'sh-alloc-net-openmail',
    sharedCostId: 'sh-net-opt',
    projectId: 'openmail',
    percentage: 20,
    allocatedAmount: 12000,
    notes: 'Inbound and outbound SMTP delivery edge routing tests.',
  },
];

// ─── 3. Direct Operating Costs (FY2026) ───────────────────────────────────────
export const initialOperatingCosts: OperatingCost[] = [
  {
    id: 'cost-dir-openmail-smtp',
    projectId: 'openmail',
    financialPeriodId: 'fy2026',
    category: 'Hosting',
    amount: 18000,
    currency: 'INR',
    directOrAllocated: 'direct',
    sourceId: 'src-infra-inv-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Dedicated SMTP outbound IP reputation blocks and reverse DNS hosting.',
  },
  {
    id: 'cost-dir-mercura-storage',
    projectId: 'mercura',
    financialPeriodId: 'fy2026',
    category: 'Storage',
    amount: 14000,
    currency: 'INR',
    directOrAllocated: 'direct',
    sourceId: 'src-infra-inv-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Dedicated NVMe volume for repository packfiles and snapshot caching.',
  },
  {
    id: 'cost-dir-m31a-compute',
    projectId: 'm31a',
    financialPeriodId: 'fy2026',
    category: 'Cloud',
    amount: 32000,
    currency: 'INR',
    directOrAllocated: 'direct',
    sourceId: 'src-infra-inv-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Dedicated execution sandbox for autonomous agent verification.',
  },
  {
    id: 'cost-dir-octate-domains',
    projectId: 'octate',
    financialPeriodId: 'fy2026',
    category: 'Domains',
    amount: 4000,
    currency: 'INR',
    directOrAllocated: 'direct',
    sourceId: 'src-gl-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Direct domain registration and dedicated SSL certificates.',
  },
  {
    id: 'cost-dir-m31genesis-storage',
    projectId: 'm31genesis',
    financialPeriodId: 'fy2026',
    category: 'Storage',
    amount: 22000,
    currency: 'INR',
    directOrAllocated: 'direct',
    sourceId: 'src-infra-inv-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Large safetensors checkpoint archival and step lineage synchronization storage.',
  },
  {
    id: 'cost-dir-m31tesla-compute',
    projectId: 'm31tesla',
    financialPeriodId: 'fy2026',
    category: 'Cloud',
    amount: 12000,
    currency: 'INR',
    directOrAllocated: 'direct',
    sourceId: 'src-infra-inv-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Python code repair evaluation test harness runtime.',
  },
  {
    id: 'cost-dir-m31entropy-disk',
    projectId: 'm31entropy',
    financialPeriodId: 'fy2026',
    category: 'Storage',
    amount: 10000,
    currency: 'INR',
    directOrAllocated: 'direct',
    sourceId: 'src-infra-inv-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Large vocabulary tokenizer token-embedding evaluation storage.',
  },
];

// ─── 4. Development Investments (FY2026) ────────────────────────────────────
// Explicit distinction between Cash Investment and Economic Development Cost.
// Founder engineering work is explicitly documented with rate methodology.
export const initialInvestments: DevelopmentInvestment[] = [
  {
    id: 'inv-openmail-dev',
    projectId: 'openmail',
    financialPeriodId: 'fy2026',
    category: 'Development',
    cashAmount: 45000,
    economicAmount: 240000,
    currency: 'INR',
    cashOrNonCash: 'mixed',
    rateMethodology:
      'Standard systems engineering economic baseline rate of ₹500/hr applied to 480 logged founder engineering hours. Not paid as cash salary.',
    sourceId: 'src-eng-log-2026',
    confidence: 'Calculated',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Foundational SMTP/IMAP protocol implementation and single-binary packaging.',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'inv-mercura-dev',
    projectId: 'mercura',
    financialPeriodId: 'fy2026',
    category: 'Development',
    cashAmount: 35000,
    economicAmount: 200000,
    currency: 'INR',
    cashOrNonCash: 'mixed',
    rateMethodology:
      'Standard systems engineering economic baseline rate of ₹500/hr applied to 400 logged founder engineering hours.',
    sourceId: 'src-eng-log-2026',
    confidence: 'Calculated',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Mercurial wire protocol engine, web UI, and local auth store development.',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'inv-m31a-dev',
    projectId: 'm31a',
    financialPeriodId: 'fy2026',
    category: 'Engineering',
    cashAmount: 65000,
    economicAmount: 310000,
    currency: 'INR',
    cashOrNonCash: 'mixed',
    rateMethodology:
      'Standard systems engineering economic baseline rate of ₹500/hr applied to 620 logged founder engineering hours.',
    sourceId: 'src-eng-log-2026',
    confidence: 'Calculated',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Autonomous developer execution framework and agent loop architecture.',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'inv-octate-dev',
    projectId: 'octate',
    financialPeriodId: 'fy2026',
    category: 'Development',
    cashAmount: 20000,
    economicAmount: 120000,
    currency: 'INR',
    cashOrNonCash: 'mixed',
    rateMethodology:
      'Standard systems engineering economic baseline rate of ₹500/hr applied to 240 logged founder engineering hours.',
    sourceId: 'src-eng-log-2026',
    confidence: 'Calculated',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Core Octate software release and operational integration.',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'inv-m31genesis-res',
    projectId: 'm31genesis',
    financialPeriodId: 'fy2026',
    category: 'Research',
    cashAmount: 30000,
    economicAmount: 180000,
    currency: 'INR',
    cashOrNonCash: 'mixed',
    rateMethodology:
      'Standard systems engineering economic baseline rate of ₹500/hr applied to 360 logged founder research hours.',
    sourceId: 'src-eng-log-2026',
    confidence: 'Calculated',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: '425M-class decoder-only transformer architecture specification and tokenizer design.',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'inv-m31tesla-res',
    projectId: 'm31tesla',
    financialPeriodId: 'fy2026',
    category: 'Research',
    cashAmount: 15000,
    economicAmount: 95000,
    currency: 'INR',
    cashOrNonCash: 'mixed',
    rateMethodology:
      'Standard systems engineering economic baseline rate of ₹500/hr applied to 190 logged founder research hours.',
    sourceId: 'src-eng-log-2026',
    confidence: 'Calculated',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Python agent 228.9M parameter runtime and repair checkpoint training.',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'inv-m31entropy-res',
    projectId: 'm31entropy',
    financialPeriodId: 'fy2026',
    category: 'Research',
    cashAmount: 10000,
    economicAmount: 70000,
    currency: 'INR',
    cashOrNonCash: 'mixed',
    rateMethodology:
      'Standard systems engineering economic baseline rate of ₹500/hr applied to 140 logged founder research hours.',
    sourceId: 'src-eng-log-2026',
    confidence: 'Calculated',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Large-vocabulary 128k tokenizer scaling exploration and pretraining dynamics.',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-01T00:00:00Z',
  },
];

// ─── 5. Engineering Hours (FY2026) ──────────────────────────────────────────
export const initialEngineeringHours: EngineeringHourRecord[] = [
  // OpenMail (480 hrs)
  {
    id: 'eng-om-01',
    projectId: 'openmail',
    personId: 'eshan-roy',
    date: '2025-10-15',
    hours: 320,
    workType: 'Development',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'SMTP/IMAP protocol implementation and storage engine.',
  },
  {
    id: 'eng-om-02',
    projectId: 'openmail',
    personId: 'eshan-roy',
    date: '2026-01-20',
    hours: 80,
    workType: 'Maintenance',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Security patches, cipher suite updates, and packaging fixes.',
  },
  {
    id: 'eng-om-03',
    projectId: 'openmail',
    personId: 'eshan-roy',
    date: '2026-02-10',
    hours: 50,
    workType: 'Security',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'TLS handshake fuzzing and spam protection integration.',
  },
  {
    id: 'eng-om-04',
    projectId: 'openmail',
    personId: 'eshan-roy',
    date: '2026-03-01',
    hours: 30,
    workType: 'Documentation',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Deployment guide and DKIM/SPF setup documentation.',
  },

  // Mercura (400 hrs)
  {
    id: 'eng-mc-01',
    projectId: 'mercura',
    personId: 'eshan-roy',
    date: '2025-11-05',
    hours: 260,
    workType: 'Development',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Mercurial wire protocol parser, repository browsing UI.',
  },
  {
    id: 'eng-mc-02',
    projectId: 'mercura',
    personId: 'eshan-roy',
    date: '2026-01-15',
    hours: 70,
    workType: 'Maintenance',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Performance tuning on large changegroups and commit index caching.',
  },
  {
    id: 'eng-mc-03',
    projectId: 'mercura',
    personId: 'eshan-roy',
    date: '2026-02-20',
    hours: 40,
    workType: 'Infrastructure',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Backup automation and multi-volume storage layout.',
  },
  {
    id: 'eng-mc-04',
    projectId: 'mercura',
    personId: 'eshan-roy',
    date: '2026-03-05',
    hours: 30,
    workType: 'Documentation',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Mercurial configuration templates and client hook guides.',
  },

  // M31A (620 hrs)
  {
    id: 'eng-m31a-01',
    projectId: 'm31a',
    personId: 'eshan-roy',
    date: '2025-09-20',
    hours: 380,
    workType: 'Development',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Autonomous agent runtime loops and tool-dispatch engine.',
  },
  {
    id: 'eng-m31a-02',
    projectId: 'm31a',
    personId: 'eshan-roy',
    date: '2025-12-10',
    hours: 140,
    workType: 'Research',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Multi-step verification mechanisms and AST diff reasoning.',
  },
  {
    id: 'eng-m31a-03',
    projectId: 'm31a',
    personId: 'eshan-roy',
    date: '2026-01-25',
    hours: 60,
    workType: 'Infrastructure',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Isolated container runtime sandboxing for code execution.',
  },
  {
    id: 'eng-m31a-04',
    projectId: 'm31a',
    personId: 'eshan-roy',
    date: '2026-02-28',
    hours: 40,
    workType: 'Testing',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Automated test harness for benchmark suites.',
  },

  // Octate (240 hrs)
  {
    id: 'eng-oct-01',
    projectId: 'octate',
    personId: 'eshan-roy',
    date: '2025-11-15',
    hours: 180,
    workType: 'Development',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Octate core system implementation and interface.',
  },
  {
    id: 'eng-oct-02',
    projectId: 'octate',
    personId: 'eshan-roy',
    date: '2026-01-30',
    hours: 30,
    workType: 'Maintenance',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Dependency maintenance and platform stability checks.',
  },
  {
    id: 'eng-oct-03',
    projectId: 'octate',
    personId: 'eshan-roy',
    date: '2026-03-02',
    hours: 30,
    workType: 'Documentation',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'System architecture reference manual.',
  },

  // M31Genesis (360 hrs)
  {
    id: 'eng-gen-01',
    projectId: 'm31genesis',
    personId: 'eshan-roy',
    date: '2025-10-01',
    hours: 240,
    workType: 'Research',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Transformer architecture tuning, 425M configuration, RoPE/GQA integration.',
  },
  {
    id: 'eng-gen-02',
    projectId: 'm31genesis',
    personId: 'eshan-roy',
    date: '2026-01-10',
    hours: 80,
    workType: 'Development',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Safetensors serialization and standalone Python inference runtime.',
  },
  {
    id: 'eng-gen-03',
    projectId: 'm31genesis',
    personId: 'eshan-roy',
    date: '2026-02-15',
    hours: 40,
    workType: 'Testing',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Checkpoint integrity verification and loss curve diagnostics.',
  },

  // M31Tesla (190 hrs)
  {
    id: 'eng-tes-01',
    projectId: 'm31tesla',
    personId: 'eshan-roy',
    date: '2025-11-20',
    hours: 110,
    workType: 'Research',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Python-Agent-220M-v5 architecture and repair token distributions.',
  },
  {
    id: 'eng-tes-02',
    projectId: 'm31tesla',
    personId: 'eshan-roy',
    date: '2026-01-18',
    hours: 60,
    workType: 'Development',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'm31_runtime.py and generation_m31.py standalone test environment.',
  },
  {
    id: 'eng-tes-03',
    projectId: 'm31tesla',
    personId: 'eshan-roy',
    date: '2026-02-22',
    hours: 20,
    workType: 'Testing',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Python regression repair benchmark execution.',
  },

  // M31Entropy (140 hrs)
  {
    id: 'eng-ent-01',
    projectId: 'm31entropy',
    personId: 'eshan-roy',
    date: '2025-12-05',
    hours: 100,
    workType: 'Research',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: '128,000 vocabulary size scaling experiments and parameter tied-embedding trade-offs.',
  },
  {
    id: 'eng-ent-02',
    projectId: 'm31entropy',
    personId: 'eshan-roy',
    date: '2026-01-28',
    hours: 30,
    workType: 'Development',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Step-00000500 checkpoint conversion and configuration scripts.',
  },
  {
    id: 'eng-ent-03',
    projectId: 'm31entropy',
    personId: 'eshan-roy',
    date: '2026-02-25',
    hours: 10,
    workType: 'Testing',
    financialPeriodId: 'fy2026',
    sourceId: 'src-eng-log-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    notes: 'Token coverage inspection and compression factor measurements.',
  },
];

// ─── 6. Project Revenue (FY2026) ────────────────────────────────────────────
// Attributed Revenue is defensible and traceable.
// Unattributed corporate revenue is preserved at the portfolio level.
// Total Corporate Revenue in FY2026 accounts: ₹18,40,000.
// Attributed: ₹5,50,000. Unattributed: ₹12,90,000.
export const initialRevenue: ProjectRevenue[] = [
  {
    id: 'rev-om-01',
    projectId: 'openmail',
    financialPeriodId: 'fy2026',
    amount: 210000,
    currency: 'INR',
    revenueType: 'Direct',
    attributionMethod: 'Direct Invoice',
    sourceId: 'src-rev-contracts-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    visibility: 'internal', // Private internal financial figure; public shows 'Not Separately Disclosed'
    notes: 'Dedicated enterprise OpenMail private instance deployment and configuration agreements.',
  },
  {
    id: 'rev-mc-01',
    projectId: 'mercura',
    financialPeriodId: 'fy2026',
    amount: 180000,
    currency: 'INR',
    revenueType: 'Direct',
    attributionMethod: 'Product Subscription',
    sourceId: 'src-rev-contracts-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    visibility: 'internal',
    notes: 'Mercura self-hosted code management license and dedicated maintenance support.',
  },
  {
    id: 'rev-m31a-01',
    projectId: 'm31a',
    financialPeriodId: 'fy2026',
    amount: 160000,
    currency: 'INR',
    revenueType: 'Direct',
    attributionMethod: 'Contract',
    sourceId: 'src-rev-contracts-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    visibility: 'internal',
    notes: 'Autonomous developer infrastructure pilot evaluation agreements.',
  },
  // Corporate Unattributed Revenue (Domain registrations, multi-tenant web hosting, networking bandwidth)
  {
    id: 'rev-corp-unatt-01',
    // No projectId: Portfolio Unattributed
    financialPeriodId: 'fy2026',
    amount: 1290000,
    currency: 'INR',
    revenueType: 'Unattributed',
    attributionMethod: 'Unattributed',
    sourceId: 'src-gl-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    visibility: 'public',
    notes:
      'Corporate infrastructure, general hosting contracts, and domain registrations not attributable to individual software projects under defensible cost-accounting rules.',
  },
];

// ─── 7. Corporate Asset Register & Operational Allocations ──────────────────
export const initialAssets: Asset[] = [
  {
    id: 'ast-srv-01',
    name: 'Primary Core Compute & Virtualization Cluster (Node Alpha)',
    assetType: 'Server',
    acquisitionDate: '2025-05-10',
    acquisitionCost: 180000,
    currency: 'INR',
    usefulLifeYears: 4,
    residualValue: 20000,
    bookValue: 150000,
    estimatedEconomicDepreciation: 30000,
    location: 'Kolkata Data Node',
    owner: 'Tonmoy Infrastructure and Vision',
    status: 'Active',
    notes: 'Multi-socket server running Proxmox virtualization for project runtimes and core daemons.',
  },
  {
    id: 'ast-net-01',
    name: 'Optical Core Router & Gateway Switch (Edge-01)',
    assetType: 'Network Equipment',
    acquisitionDate: '2025-06-01',
    acquisitionCost: 60000,
    currency: 'INR',
    usefulLifeYears: 5,
    residualValue: 10000,
    bookValue: 50000,
    estimatedEconomicDepreciation: 10000,
    location: 'Kolkata Data Node',
    owner: 'Tonmoy Infrastructure and Vision',
    status: 'Active',
    notes: '10GbE edge gateway providing redundant uplinks and BGP peering.',
  },
  {
    id: 'ast-str-01',
    name: 'High-Availability Storage Array (SAN-01)',
    assetType: 'Storage',
    acquisitionDate: '2025-07-15',
    acquisitionCost: 110000,
    currency: 'INR',
    usefulLifeYears: 4,
    residualValue: 15000,
    bookValue: 90000,
    estimatedEconomicDepreciation: 20000,
    location: 'Kolkata Data Node',
    owner: 'Tonmoy Infrastructure and Vision',
    status: 'Active',
    notes: 'ZFS mirrored storage pool backing code repositories, mail storage, and model checkpoints.',
  },
  {
    id: 'ast-lab-01',
    name: 'Research Compute Node & GPU Workstation (M31-Lab)',
    assetType: 'Laboratory Equipment',
    acquisitionDate: '2025-08-20',
    acquisitionCost: 140000,
    currency: 'INR',
    usefulLifeYears: 3,
    residualValue: 20000,
    bookValue: 115000,
    estimatedEconomicDepreciation: 25000,
    location: 'TIV Systems Engineering Lab',
    owner: 'Tonmoy Infrastructure and Vision',
    status: 'Active',
    notes: 'Experimental workstation for local model evaluation, tokenizer benchmarking, and AST generation.',
  },
];

export const initialAssetAllocations: AssetAllocation[] = [
  // Primary Server Cluster (ast-srv-01) - sum = 100%
  {
    id: 'ast-alloc-srv-om',
    assetId: 'ast-srv-01',
    projectId: 'openmail',
    periodId: 'fy2026',
    allocationPercentage: 30,
    allocationBasis: 'Compute',
    notes: '30% of virtualization compute dedicated to mail transport and inbox storage daemons.',
  },
  {
    id: 'ast-alloc-srv-mc',
    assetId: 'ast-srv-01',
    projectId: 'mercura',
    periodId: 'fy2026',
    allocationPercentage: 25,
    allocationBasis: 'Compute',
    notes: '25% of virtualization compute allocated to Mercurial web services.',
  },
  {
    id: 'ast-alloc-srv-m31a',
    assetId: 'ast-srv-01',
    projectId: 'm31a',
    periodId: 'fy2026',
    allocationPercentage: 35,
    allocationBasis: 'Compute',
    notes: '35% of virtualization compute allocated to M31A agent orchestration.',
  },
  {
    id: 'ast-alloc-srv-oct',
    assetId: 'ast-srv-01',
    projectId: 'octate',
    periodId: 'fy2026',
    allocationPercentage: 10,
    allocationBasis: 'Compute',
    notes: '10% of virtualization compute allocated to Octate runtime.',
  },

  // Optical Core Router (ast-net-01) - sum = 100%
  {
    id: 'ast-alloc-net-m31a',
    assetId: 'ast-net-01',
    projectId: 'm31a',
    periodId: 'fy2026',
    allocationPercentage: 50,
    allocationBasis: 'Bandwidth',
    notes: 'High-throughput telemetry and continuous code evaluation streams.',
  },
  {
    id: 'ast-alloc-net-mc',
    assetId: 'ast-net-01',
    projectId: 'mercura',
    periodId: 'fy2026',
    allocationPercentage: 25,
    allocationBasis: 'Bandwidth',
    notes: 'Mercurial client clone and pull network traffic.',
  },
  {
    id: 'ast-alloc-net-om',
    assetId: 'ast-net-01',
    projectId: 'openmail',
    periodId: 'fy2026',
    allocationPercentage: 25,
    allocationBasis: 'Bandwidth',
    notes: 'Inbound and outbound SMTP/IMAP network transit.',
  },

  // Storage Array (ast-str-01) - sum = 100%
  {
    id: 'ast-alloc-str-mc',
    assetId: 'ast-str-01',
    projectId: 'mercura',
    periodId: 'fy2026',
    allocationPercentage: 40,
    allocationBasis: 'Storage',
    notes: 'Repository changegroup packfiles and branch commit histories.',
  },
  {
    id: 'ast-alloc-str-om',
    assetId: 'ast-str-01',
    projectId: 'openmail',
    periodId: 'fy2026',
    allocationPercentage: 30,
    allocationBasis: 'Storage',
    notes: 'Mailbox stores and local message archives.',
  },
  {
    id: 'ast-alloc-str-gen',
    assetId: 'ast-str-01',
    projectId: 'm31genesis',
    periodId: 'fy2026',
    allocationPercentage: 20,
    allocationBasis: 'Storage',
    notes: 'Step-00000500 to latest safetensors checkpoints archive.',
  },
  {
    id: 'ast-alloc-str-tes',
    assetId: 'ast-str-01',
    projectId: 'm31tesla',
    periodId: 'fy2026',
    allocationPercentage: 10,
    allocationBasis: 'Storage',
    notes: 'Python agent checkpoint revisions and evaluation logs.',
  },

  // Research Workstation (ast-lab-01) - sum = 100%
  {
    id: 'ast-alloc-lab-gen',
    assetId: 'ast-lab-01',
    projectId: 'm31genesis',
    periodId: 'fy2026',
    allocationPercentage: 60,
    allocationBasis: 'Compute',
    notes: 'M31Genesis 425M inference benchmarking and token-level loss analysis.',
  },
  {
    id: 'ast-alloc-lab-tes',
    assetId: 'ast-lab-01',
    projectId: 'm31tesla',
    periodId: 'fy2026',
    allocationPercentage: 25,
    allocationBasis: 'Compute',
    notes: 'M31Tesla Python agent code repair execution testing.',
  },
  {
    id: 'ast-alloc-lab-ent',
    assetId: 'ast-lab-01',
    projectId: 'm31entropy',
    periodId: 'fy2026',
    allocationPercentage: 15,
    allocationBasis: 'Compute',
    notes: '128k vocabulary tokenizer training and compression measurements.',
  },
];

// ─── 8. Research Expenditures (FY2026) ──────────────────────────────────────
export const initialResearchExpenditures: ResearchExpenditure[] = [
  {
    id: 'res-exp-m31gen-data',
    projectId: 'm31genesis',
    financialPeriodId: 'fy2026',
    researchAreaSlug: 'artificial-intelligence',
    category: 'Datasets',
    amount: 25000,
    currency: 'INR',
    sourceId: 'src-gl-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Code syntax AST curation and tokenization pre-filtering datasets.',
  },
  {
    id: 'res-exp-m31gen-compute',
    projectId: 'm31genesis',
    financialPeriodId: 'fy2026',
    researchAreaSlug: 'artificial-intelligence',
    category: 'Compute',
    amount: 20000,
    currency: 'INR',
    sourceId: 'src-infra-inv-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Specialized compute instances for checkpoint validation runs.',
  },
  {
    id: 'res-exp-m31tes-tools',
    projectId: 'm31tesla',
    financialPeriodId: 'fy2026',
    researchAreaSlug: 'artificial-intelligence',
    category: 'Research Software',
    amount: 18000,
    currency: 'INR',
    sourceId: 'src-gl-2026',
    confidence: 'Verified',
    approvalStatus: 'Published',
    visibility: 'public',
    notes: 'Static analysis and AST mutation diagnostic software for Python code repair.',
  },
];

// ─── 9. Strategic Assessments (1–5 Scores — NOT Monetary Valuation) ─────────
export const initialStrategicAssessments: StrategicAssessment[] = [
  {
    id: 'strat-om',
    projectId: 'openmail',
    assessmentDate: '2026-04-01',
    assessor: 'Eshan Roy (Founder)',
    strategicImportance: 4,
    technicalDifferentiation: 4,
    infrastructureRelevance: 5,
    researchSignificance: 2,
    revenuePotential: 4,
    ecosystemImportance: 5,
    notes:
      'Foundational communication infrastructure. Solves sovereign email hosting without central vendor lock-in. Essential pillar of TIV sovereign cloud.',
  },
  {
    id: 'strat-mc',
    projectId: 'mercura',
    assessmentDate: '2026-04-01',
    assessor: 'Eshan Roy (Founder)',
    strategicImportance: 4,
    technicalDifferentiation: 4,
    infrastructureRelevance: 4,
    researchSignificance: 2,
    revenuePotential: 3,
    ecosystemImportance: 4,
    notes:
      'Provides independent, self-hosted code collaboration using Mercurial. Anchors internal repository sovereignty.',
  },
  {
    id: 'strat-m31a',
    projectId: 'm31a',
    assessmentDate: '2026-04-01',
    assessor: 'Eshan Roy (Founder)',
    strategicImportance: 5,
    technicalDifferentiation: 5,
    infrastructureRelevance: 5,
    researchSignificance: 5,
    revenuePotential: 5,
    ecosystemImportance: 5,
    notes:
      'Core autonomous development and AI infrastructure system. Highest technical leverage in the portfolio; connects systems engineering with autonomous coding.',
  },
  {
    id: 'strat-oct',
    projectId: 'octate',
    assessmentDate: '2026-04-01',
    assessor: 'Eshan Roy (Founder)',
    strategicImportance: 3,
    technicalDifferentiation: 3,
    infrastructureRelevance: 3,
    researchSignificance: 2,
    revenuePotential: 3,
    ecosystemImportance: 3,
    notes: 'Stable software component complementing TIV developer and systems portfolio.',
  },
  {
    id: 'strat-gen',
    projectId: 'm31genesis',
    assessmentDate: '2026-04-01',
    assessor: 'Eshan Roy (Founder)',
    strategicImportance: 5,
    technicalDifferentiation: 5,
    infrastructureRelevance: 4,
    researchSignificance: 5,
    revenuePotential: 2,
    ecosystemImportance: 4,
    notes:
      'Native M31 causal language model for agentic coding research. Fundamental research asset exploring sovereign, inspectable model architectures.',
  },
  {
    id: 'strat-tes',
    projectId: 'm31tesla',
    assessmentDate: '2026-04-01',
    assessor: 'Eshan Roy (Founder)',
    strategicImportance: 4,
    technicalDifferentiation: 4,
    infrastructureRelevance: 3,
    researchSignificance: 4,
    revenuePotential: 2,
    ecosystemImportance: 3,
    notes:
      'Python agent runtime and repair checkpoint research. High experimental value for automated regression patching.',
  },
  {
    id: 'strat-ent',
    projectId: 'm31entropy',
    assessmentDate: '2026-04-01',
    assessor: 'Eshan Roy (Founder)',
    strategicImportance: 4,
    technicalDifferentiation: 4,
    infrastructureRelevance: 3,
    researchSignificance: 4,
    revenuePotential: 2,
    ecosystemImportance: 3,
    notes:
      'Large vocabulary tokenizer scaling exploration. Informs tokenizer density and AST embedding architectures across M31.',
  },
];
