export interface DataCenterSpecs {
  servers: number;
  racks: number;
  coolingCapacity: number; // in MW
  backupGenerators: number;
}

export interface DataCenterFacility {
  name: string;
  country: string;
  region: string;
  status: 'Operational' | 'Degraded' | 'Maintenance';
  tier: 'Tier 4' | 'Tier 3';
  certifications: string[];
  powerCapacity: number; // MW
  redundancy: string;
  networkProviders: string[];
  load: number; // Percentage
  lat: number;
  lng: number;
  totalStorage: number; // In TB (65000 = 65 PB)
  usedStorage: number;
  specs: DataCenterSpecs;
}

export interface CourierHub {
  name: string;
  country: string;
  region: string;
  lat: number;
  lng: number;
  status: string;
  certifications: string[];
  partners: string[];
  load: number;
}

export interface LogisticsService {
  title: string;
  tagline: string;
  description: string;
  features: string[];
}

export interface LogisticsKpi {
  label: string;
  value: string;
  description: string;
}

// ─── 16 Global Data Centers Fleet ───────────────────────────

export const DATA_CENTERS: DataCenterFacility[] = [
  {
    name: 'New York',
    country: 'United States',
    region: 'North America',
    status: 'Operational',
    tier: 'Tier 4',
    certifications: ['ISO 27001', 'PCI DSS', 'SOC 2', 'HIPAA'],
    powerCapacity: 70,
    redundancy: '2N+2',
    networkProviders: ['Verizon', 'AT&T', 'Sprint'],
    load: 92,
    lat: 40.7128,
    lng: -74.006,
    totalStorage: 65000,
    usedStorage: 56000,
    specs: {
      servers: 22000,
      racks: 2000,
      coolingCapacity: 65,
      backupGenerators: 14,
    },
  },
  {
    name: 'Silicon Valley',
    country: 'United States',
    region: 'North America',
    status: 'Operational',
    tier: 'Tier 4',
    certifications: ['ISO 27001', 'PCI DSS', 'SOC 2', 'HIPAA'],
    powerCapacity: 75,
    redundancy: '2N+2',
    networkProviders: ['AT&T', 'Comcast', 'Level 3'],
    load: 88,
    lat: 37.3875,
    lng: -122.0575,
    totalStorage: 70000,
    usedStorage: 58000,
    specs: {
      servers: 24000,
      racks: 2200,
      coolingCapacity: 70,
      backupGenerators: 16,
    },
  },
  {
    name: 'Dallas',
    country: 'United States',
    region: 'North America',
    status: 'Operational',
    tier: 'Tier 4',
    certifications: ['ISO 27001', 'PCI DSS', 'SOC 2'],
    powerCapacity: 65,
    redundancy: '2N+2',
    networkProviders: ['AT&T', 'Verizon', 'CenturyLink'],
    load: 85,
    lat: 32.7767,
    lng: -96.797,
    totalStorage: 55000,
    usedStorage: 45000,
    specs: {
      servers: 18000,
      racks: 1600,
      coolingCapacity: 60,
      backupGenerators: 12,
    },
  },
  {
    name: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    status: 'Operational',
    tier: 'Tier 4',
    certifications: ['ISO 27001', 'PCI DSS', 'SOC 2', 'GDPR Compliant'],
    powerCapacity: 65,
    redundancy: '2N+2',
    networkProviders: ['BT', 'Vodafone', 'Three'],
    load: 89,
    lat: 51.5074,
    lng: -0.1278,
    totalStorage: 62000,
    usedStorage: 53000,
    specs: {
      servers: 20000,
      racks: 1800,
      coolingCapacity: 60,
      backupGenerators: 12,
    },
  },
  {
    name: 'Frankfurt',
    country: 'Germany',
    region: 'Europe',
    status: 'Operational',
    tier: 'Tier 4',
    certifications: ['ISO 27001', 'PCI DSS', 'SOC 2', 'GDPR Compliant'],
    powerCapacity: 60,
    redundancy: '2N+2',
    networkProviders: ['Deutsche Telekom', 'Vodafone', 'O2'],
    load: 90,
    lat: 50.1109,
    lng: 8.6821,
    totalStorage: 58000,
    usedStorage: 49000,
    specs: {
      servers: 18000,
      racks: 1600,
      coolingCapacity: 55,
      backupGenerators: 12,
    },
  },
  {
    name: 'Amsterdam',
    country: 'Netherlands',
    region: 'Europe',
    status: 'Operational',
    tier: 'Tier 4',
    certifications: ['ISO 27001', 'PCI DSS', 'SOC 2', 'GDPR Compliant'],
    powerCapacity: 55,
    redundancy: '2N+2',
    networkProviders: ['KPN', 'Vodafone', 'T-Mobile'],
    load: 87,
    lat: 52.3676,
    lng: 4.9041,
    totalStorage: 50000,
    usedStorage: 42000,
    specs: {
      servers: 16000,
      racks: 1400,
      coolingCapacity: 50,
      backupGenerators: 10,
    },
  },
  {
    name: 'Tokyo',
    country: 'Japan',
    region: 'East Asia',
    status: 'Operational',
    tier: 'Tier 4',
    certifications: ['ISO 27001', 'PCI DSS', 'SOC 2'],
    powerCapacity: 55,
    redundancy: '2N+1',
    networkProviders: ['NTT', 'KDDI', 'SoftBank'],
    load: 88,
    lat: 35.6762,
    lng: 139.6503,
    totalStorage: 52000,
    usedStorage: 44000,
    specs: {
      servers: 16000,
      racks: 1400,
      coolingCapacity: 50,
      backupGenerators: 10,
    },
  },
  {
    name: 'Seoul',
    country: 'South Korea',
    region: 'East Asia',
    status: 'Operational',
    tier: 'Tier 4',
    certifications: ['ISO 27001', 'PCI DSS', 'SOC 2'],
    powerCapacity: 50,
    redundancy: '2N+1',
    networkProviders: ['SK Telecom', 'KT', 'LG U+'],
    load: 86,
    lat: 37.5665,
    lng: 126.978,
    totalStorage: 48000,
    usedStorage: 40000,
    specs: {
      servers: 15000,
      racks: 1300,
      coolingCapacity: 45,
      backupGenerators: 9,
    },
  },
  {
    name: 'Singapore Central',
    country: 'Singapore',
    region: 'Southeast Asia',
    status: 'Operational',
    tier: 'Tier 4',
    certifications: ['ISO 27001', 'PCI DSS', 'SOC 2', 'SS 564'],
    powerCapacity: 60,
    redundancy: '2N+2',
    networkProviders: ['Singtel', 'StarHub', 'M1'],
    load: 91,
    lat: 1.3521,
    lng: 103.8198,
    totalStorage: 55000,
    usedStorage: 47000,
    specs: {
      servers: 18000,
      racks: 1500,
      coolingCapacity: 55,
      backupGenerators: 10,
    },
  },
  {
    name: 'Mumbai',
    country: 'India',
    region: 'South Asia',
    status: 'Operational',
    tier: 'Tier 4',
    certifications: ['ISO 27001', 'PCI DSS', 'SOC 2'],
    powerCapacity: 50,
    redundancy: '2N+1',
    networkProviders: ['Airtel', 'Tata', 'Reliance'],
    load: 78,
    lat: 19.076,
    lng: 72.8777,
    totalStorage: 50000,
    usedStorage: 39000,
    specs: {
      servers: 15000,
      racks: 1200,
      coolingCapacity: 45,
      backupGenerators: 8,
    },
  },
  {
    name: 'Bangalore',
    country: 'India',
    region: 'South Asia',
    status: 'Operational',
    tier: 'Tier 4',
    certifications: ['ISO 27001', 'PCI DSS', 'SOC 2'],
    powerCapacity: 45,
    redundancy: '2N+1',
    networkProviders: ['Airtel', 'Jio', 'BSNL'],
    load: 82,
    lat: 12.9716,
    lng: 77.5946,
    totalStorage: 45000,
    usedStorage: 36000,
    specs: {
      servers: 14000,
      racks: 1100,
      coolingCapacity: 40,
      backupGenerators: 8,
    },
  },
  {
    name: 'Dhaka',
    country: 'Bangladesh',
    region: 'South Asia',
    status: 'Operational',
    tier: 'Tier 3',
    certifications: ['ISO 27001', 'PCI DSS'],
    powerCapacity: 40,
    redundancy: '2N',
    networkProviders: ['BTCL', 'Link3', 'BanglaNet'],
    load: 75,
    lat: 23.8103,
    lng: 90.4125,
    totalStorage: 40000,
    usedStorage: 28000,
    specs: {
      servers: 12000,
      racks: 1000,
      coolingCapacity: 35,
      backupGenerators: 6,
    },
  },
  {
    name: 'Chittagong',
    country: 'Bangladesh',
    region: 'South Asia',
    status: 'Operational',
    tier: 'Tier 3',
    certifications: ['ISO 27001', 'PCI DSS'],
    powerCapacity: 35,
    redundancy: '2N',
    networkProviders: ['BTCL', 'Link3'],
    load: 70,
    lat: 22.3569,
    lng: 91.7832,
    totalStorage: 35000,
    usedStorage: 22000,
    specs: {
      servers: 10000,
      racks: 800,
      coolingCapacity: 30,
      backupGenerators: 5,
    },
  },
  {
    name: 'Satkhira',
    country: 'Bangladesh',
    region: 'South Asia',
    status: 'Operational',
    tier: 'Tier 3',
    certifications: ['ISO 27001'],
    powerCapacity: 30,
    redundancy: 'N+1',
    networkProviders: ['BTCL', 'Link3'],
    load: 65,
    lat: 22.7185,
    lng: 89.0705,
    totalStorage: 30000,
    usedStorage: 18000,
    specs: {
      servers: 8000,
      racks: 600,
      coolingCapacity: 25,
      backupGenerators: 4,
    },
  },
  {
    name: 'Sydney',
    country: 'Australia',
    region: 'Oceania',
    status: 'Operational',
    tier: 'Tier 4',
    certifications: ['ISO 27001', 'PCI DSS', 'SOC 2'],
    powerCapacity: 45,
    redundancy: '2N+1',
    networkProviders: ['Telstra', 'Optus', 'TPG'],
    load: 80,
    lat: -33.8688,
    lng: 151.2093,
    totalStorage: 45000,
    usedStorage: 35000,
    specs: {
      servers: 14000,
      racks: 1200,
      coolingCapacity: 40,
      backupGenerators: 8,
    },
  },
  {
    name: 'Melbourne',
    country: 'Australia',
    region: 'Oceania',
    status: 'Operational',
    tier: 'Tier 4',
    certifications: ['ISO 27001', 'PCI DSS', 'SOC 2'],
    powerCapacity: 40,
    redundancy: '2N+1',
    networkProviders: ['Telstra', 'Optus', 'Vodafone'],
    load: 78,
    lat: -37.8136,
    lng: 144.9631,
    totalStorage: 40000,
    usedStorage: 30000,
    specs: {
      servers: 12000,
      racks: 1000,
      coolingCapacity: 35,
      backupGenerators: 7,
    },
  },
];

// ─── 17 Global Courier Network Hubs ─────────────────────────

export const COURIER_HUBS: CourierHub[] = [
  {
    name: 'New York Hub',
    country: 'United States',
    region: 'North America',
    lat: 37.0902,
    lng: -95.7129,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['FedEx', 'UPS', 'USPS Direct'],
    load: 88,
  },
  {
    name: 'London Heathrow Gateway',
    country: 'United Kingdom',
    region: 'Europe',
    lat: 55.3781,
    lng: -3.436,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['Royal Mail', 'DHL UK', 'DPD'],
    load: 85,
  },
  {
    name: 'Frankfurt Central Hub',
    country: 'Germany',
    region: 'Europe',
    lat: 51.1657,
    lng: 10.4515,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['Deutsche Post', 'Hermes', 'GLS'],
    load: 87,
  },
  {
    name: 'Paris Charles de Gaulle Node',
    country: 'France',
    region: 'Europe',
    lat: 46.2276,
    lng: 2.2137,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['La Poste', 'Chronopost'],
    load: 82,
  },
  {
    name: 'Madrid Barajas Facility',
    country: 'Spain',
    region: 'Europe',
    lat: 40.4637,
    lng: -3.7492,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['Correos Express', 'SEUR'],
    load: 79,
  },
  {
    name: 'Milan Malpensa Hub',
    country: 'Italy',
    region: 'Europe',
    lat: 41.8719,
    lng: 12.5674,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['Poste Italiane', 'BRT'],
    load: 81,
  },
  {
    name: 'Tokyo Narita Hub',
    country: 'Japan',
    region: 'East Asia',
    lat: 36.2048,
    lng: 138.2529,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['Yamato Transport', 'Sagawa Express', 'Japan Post'],
    load: 86,
  },
  {
    name: 'Seoul Incheon Logistics Center',
    country: 'South Korea',
    region: 'East Asia',
    lat: 35.9078,
    lng: 127.7669,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['CJ Logistics', 'Korea Post', 'Hanjin'],
    load: 84,
  },
  {
    name: 'Shanghai Pudong Hub',
    country: 'China',
    region: 'East Asia',
    lat: 35.8617,
    lng: 104.1954,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['SF Express', 'China Post', 'ZTO'],
    load: 91,
  },
  {
    name: 'Mumbai International Freight Center',
    country: 'India',
    region: 'South Asia',
    lat: 20.5937,
    lng: 78.9629,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['Blue Dart', 'India Post', 'Delhivery'],
    load: 85,
  },
  {
    name: 'Sydney Kingsford Gateway',
    country: 'Australia',
    region: 'Oceania',
    lat: -25.2744,
    lng: 133.7751,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['Australia Post', 'StarTrack', 'Toll'],
    load: 80,
  },
  {
    name: 'São Paulo Viracopos Node',
    country: 'Brazil',
    region: 'South America',
    lat: -14.235,
    lng: -51.9253,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['Correios', 'Total Express', 'Jadlog'],
    load: 76,
  },
  {
    name: 'Toronto Pearson Hub',
    country: 'Canada',
    region: 'North America',
    lat: 56.1304,
    lng: -106.3468,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['Canada Post', 'Purolator'],
    load: 83,
  },
  {
    name: 'Singapore Changi Air Cargo Hub',
    country: 'Singapore',
    region: 'Southeast Asia',
    lat: 1.3521,
    lng: 103.8198,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['SingPost', 'Ninja Van'],
    load: 89,
  },
  {
    name: 'Dubai Al Maktoum Logistics Hub',
    country: 'UAE',
    region: 'Middle East',
    lat: 23.4241,
    lng: 53.8478,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['Emirates Post', 'Aramex'],
    load: 84,
  },
  {
    name: 'Johannesburg O.R. Tambo Facility',
    country: 'South Africa',
    region: 'Africa',
    lat: -30.5595,
    lng: 22.9375,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['South African Post Office', 'RAM', 'Dawn Wing'],
    load: 75,
  },
  {
    name: 'Dhaka Shahjalal Cargo Hub',
    country: 'Bangladesh',
    region: 'South Asia',
    lat: 23.685,
    lng: 90.3563,
    status: 'Active Hub',
    certifications: ['ISO 9001', 'GDP'],
    partners: ['Biman Cargo', 'SA Paribahan', 'Sundarban Courier'],
    load: 86,
  },
];

// ─── Logistics Performance Metrics ──────────────────────────

export const COURIER_METRICS: LogisticsKpi[] = [
  {
    label: 'Daily Shipments',
    value: '50,000+',
    description: 'Parcels, equipment, and secure documents handled per day across international routes.',
  },
  {
    label: 'Countries Served',
    value: '17',
    description: 'Fully certified and operational primary international logistics and customs hubs.',
  },
  {
    label: 'Average Delivery Time',
    value: '48h',
    description: 'Guaranteed cross-border transit turnaround to major metropolitan centers worldwide.',
  },
  {
    label: 'Success Rate',
    value: '99.9%',
    description: 'Verified fulfillment, handling integrity, and on-time distribution reliability.',
  },
];

// ─── Logistics Service Pillars ──────────────────────────────

export const COURIER_SERVICES: LogisticsService[] = [
  {
    title: 'Express Delivery',
    tagline: 'Rapid Worldwide Transit',
    description: '48-hour delivery guarantee to major global metropolitan cities with complete tracking transparency.',
    features: [
      'Door-to-door direct courier service',
      'Real-time cryptographic parcel tracking',
      'Full transit replacement insurance included',
      'Automated dispatch & pickup scheduling',
    ],
  },
  {
    title: 'Customs Clearance',
    tagline: 'Frictionless Regulatory Flow',
    description: 'Hassle-free customs processing leveraging regional regulatory compliance and automated classification.',
    features: [
      'Full import/export documentation support',
      'Automated duty and tariff calculation',
      'Regulatory compliance & HS-code handling',
      'Bilingual clearance agents on-site',
    ],
  },
  {
    title: 'Specialized Handling',
    tagline: 'Precision Climate & Security Care',
    description: 'Customized logistics protocols for high-value hardware, sensitive electronics, cold chain, and oversized freight.',
    features: [
      'Temperature-controlled pharmaceutical & wafer cold chain',
      'Anti-static and fragile hardware packaging',
      'Oversized enterprise rack & server cargo transit',
      'Tamper-evident physical security seals',
    ],
  },
];
